# action.yml
name: 'AUR publish docker'
description: 'Publish an AUR package'
inputs:
  package_name:
    description: 'AUR package name'
    required: true
  commit_username:
    description: 'The username to use when creating the new commit.'
    required: true
  commit_email:
    description: 'The email to use when creating the new commit.'
    required: true
  ssh_private_key:
    description: 'Your private key with access to AUR package.'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.package_name }} ${{ github.ref }} ${{ inputs.commit_username }} ${{ inputs.commit_email }} ${{ inputs.ssh_private_key }}
